# This file exists within 'pep440-version-compare-cli' aka 'pep440cmp':
#
#   https://github.com/hotoffthehamster/pep440-version-compare-cli

version: 2

python:
  version: 3.7
  install:
     - method: pip
       path: .

