# This file exists within 'pep440-version-compare-cli' aka 'pep440cmp':
#
#   https://github.com/hotoffthehamster/pep440-version-compare-cli

codecov:
  branch: develop
  # (lb): With setting disable_default_path_fixes, I see:
  #   "There was an error processing coverage reports."
  # Strangely, I find exactly 7 hits when I Goggle this keyname.
  # And they all point to a codecov issue comment:
  #   https://github.com/codecov/support/issues/396#issuecomment-300879528
  # which is a dead link!
  # There are a few score more hits on GitHub proper:
  #   https://github.com/search?l=&q=disable_default_path_fixes&type=Code
  # but still solely yaml results. I.e., cannot find application source
  # that reads/uses this value.
  # - Is this an undocumented, proprietary https://codecov.io setting?
  disable_default_path_fixes: true

# Specify the GitHub project directory path prefix so that clicking source
# files in codecov.io opens the coverage browser.
fixes:
  - "::pep440cmp/"

coverage:
  # precision: 0 | 2
  precision: 0
  # round: [down] | up | nearest
  range: 70...100

